version: '3.8'

services:
  app:
    build: .
    image: emsp:latest
    container_name: emsp
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      DATASOURCE_URL: db:3306
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: emsp
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

volumes:
  mysql_data:
