version: '3.8'

services:
  app:
    build: .
    image: emsp:latest
    container_name: emsp
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: emsp
      WORKER_ID: 0
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: emsp
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

volumes:
  mysql_data:
