spring:
  application:
    name: eMSP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 50
    scheduling:
      pool:
        size: 2

springdoc:
  swagger-ui:
    path: /index.html

app:
  id: ${WORKER_ID}